apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: edusmart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 590144423099.dkr.ecr.ap-southeast-2.amazonaws.com/edusmart-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: edusmart-config
            - secretRef:
                name: edusmart-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"