version: '3.8'

services:


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: edusmart-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_PORT=${APP_PORT:-8080}
      - JWT_SECRET=${JWT_SECRET:-supersecret}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME:-avatars}


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: edusmart-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend


