apiVersion: apps/v1
kind: Deployment
metadata:
  name: edusmart-frontend
  labels:
    app: edusmart-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edusmart-frontend
  template:
    metadata:
      labels:
        app: edusmart-frontend
    spec:
      containers:
      - name: edusmart-frontend
        image: edusmart-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
