apiVersion: v1
kind: Service
metadata:
  name: edusmart-frontend
  labels:
    app: edusmart-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: edusmart-frontend
