name: CI/CD EduSmart

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/edusmart-frontend:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/edusmart-frontend:$IMAGE_TAG
          echo "FRONTEND_IMAGE=$ECR_REGISTRY/edusmart-frontend:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build & push backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/edusmart-backend:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/edusmart-backend:$IMAGE_TAG
          echo "BACKEND_IMAGE=$ECR_REGISTRY/edusmart-backend:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/frontend \
            frontend=$ECR_REGISTRY/edusmart-frontend:$IMAGE_TAG \
            -n edusmart
          kubectl set image deployment/backend \
            backend=$ECR_REGISTRY/edusmart-backend:$IMAGE_TAG \
            -n edusmart
          kubectl rollout status deployment/frontend -n edusmart
          kubectl rollout status deployment/backend -n edusmart